brace_style="AlwaysNextLine"
combine_control_expr=false
condense_wildcard_suffixes=true
control_brace_style="AlwaysNextLine"
empty_item_single_line=false
fn_params_layout="Vertical"
fn_single_line=false
force_explicit_abi=true
format_code_in_doc_comments=true
format_generated_files=false
hard_tabs=false
hex_literal_case="Upper"
imports_indent="Visual"
imports_layout="Vertical"
indent_style="Block"
inline_attribute_width=0
imports_granularity="Crate"
normalize_comments=true
overflow_delimited_expr=true
group_imports="StdExternalCrate"
single_line_let_else_max_width=0
space_after_colon=true
space_before_colon=false
struct_lit_single_line=false
tab_spaces=4
trailing_comma="Never"
trailing_semicolon=true
where_single_line=false
wrap_comments=true
